### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by chrisgilmerproj** [sbuss/TigerShark#10]
Can we push this package to PyPI? It would be nice to install this package via pip in a requirements.txt file instead of the clone/install two-step.

**Comment by chrisgilmerproj** [comment]
@sbuss - Can we get this up to PyPI by next week maybe?

**Comment by sbuss** [comment]
Uploaded today: https://pypi.python.org/pypi/TigerShark/0.2.6

**Comment by chrisgilmerproj** [comment]
Thanks!  I really appreciate it.
